# Generated by Django 4.2.6 on 2023-10-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='user',
            field=models.CharField(default='sambhu', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todos',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
